version: '3.7'

networks:
  lan_microservices:

services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8083:8080
    networks:
      - lan_microservices

  db:
    image: postgres
    container_name: postgres_synergy
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    networks:
      - lan_microservices